In [2]:
import gym

In [3]:
# gym contains various environment, one of the environment is cart-pole that we ll use
# its the game env in whivh a sticks tries to balance itself
env = gym.make('CartPole-v0')

[2017-09-23 21:59:31,771] Making new env: CartPole-v0


In [4]:
# an episode is one complete cycle of the game, ie, here after the sticks falls, one episode 
# is completed. We can learn after episode

env.reset()
for iEpisode in range(20):
    
    # we ll reset the env after each episodeit over and take the output of the episode in 
    # the observation. In our case observation will be simply an array of velocities
    observation = env.reset()
    
    # we ll b having 100 time steps in each episode
    for tSteps in range(100):
        env.render()
        print(observation)
        
        #now we ll take an action in the step
        action = env.action_space.sample()
        
        observation, reward, done, info = env.step(action)
        
        if done:
            print('Episode died after {} timesteps '.format(tSteps))
            break
    

[-0.01979235  0.01626114 -0.02634243  0.03110073]
[-0.01946713 -0.17847334 -0.02572041  0.31535732]
[-0.02303659  0.01700537 -0.01941326  0.01467529]
[-0.02269649  0.21240027 -0.01911976 -0.28406898]
[-0.01844848  0.01755616 -0.02480114  0.00252289]
[-0.01809736  0.21302486 -0.02475068 -0.29788077]
[-0.01383686  0.40849072 -0.0307083  -0.59826572]
[-0.00566705  0.60402859 -0.04267361 -0.90046106]
[ 0.00641353  0.799702   -0.06068283 -1.2062462 ]
[ 0.02240757  0.9955533  -0.08480776 -1.51731222]
[ 0.04231863  1.19159251 -0.115154   -1.83521779]
[ 0.06615048  1.38778431 -0.15185836 -2.16133696]
[ 0.09390617  1.19444122 -0.19508509 -1.91913486]
Episode died after 12 timesteps 
[-0.00684624 -0.04887266 -0.04449263  0.01860559]
[-0.00782369  0.14685819 -0.04412051 -0.28777665]
[-0.00488653 -0.04760771 -0.04987605 -0.00932889]
[-0.00583868 -0.24198021 -0.05006262  0.2672098 ]
[-0.01067829 -0.43635326 -0.04471843  0.54369183]
[-0.01940535 -0.63081919 -0.03384459  0.82195628]
[-0.03202173 -0.8

[-0.03194853 -0.15157356  0.03274178  0.33711481]
[-0.03498     0.04306753  0.03948408  0.05493402]
[-0.03411865 -0.15259767  0.04058276  0.35980837]
[-0.0371706  -0.3482723   0.04777893  0.66500671]
[-0.04413605 -0.15384637  0.06107906  0.38774229]
[-0.04721298 -0.34977974  0.06883391  0.69904037]
[-0.05420857 -0.54578512  0.08281471  1.01257339]
[-0.06512427 -0.74190839  0.10306618  1.33006978]
[-0.07996244 -0.54822655  0.12966758  1.07133656]
[-0.09092697 -0.74480207  0.15109431  1.40173997]
[-0.10582301 -0.94144358  0.17912911  1.73759461]
Episode died after 11 timesteps 
[ 0.04198892 -0.03887331  0.02790972  0.00202828]
[ 0.04121145 -0.23438418  0.02795028  0.30338476]
[ 0.03652377 -0.03967149  0.03401798  0.01964611]
[ 0.03573034 -0.23526436  0.0344109   0.32286504]
[ 0.03102505 -0.43085899  0.0408682   0.6261981 ]
[ 0.02240787 -0.23633063  0.05339216  0.3466611 ]
[ 0.01768126 -0.04200718  0.06032538  0.07128115]
[ 0.01684112 -0.23793978  0.06175101  0.38237034]
[ 0.01208232 -0.4

[ 0.1193552   0.75772307 -0.08057257 -0.81353933]
[ 0.13450966  0.5637916  -0.09684336 -0.54724858]
[ 0.14578549  0.76013119 -0.10778833 -0.86880546]
[ 0.16098812  0.56662778 -0.12516444 -0.61186329]
[ 0.17232067  0.37345686 -0.1374017  -0.36107597]
[ 0.17978981  0.18052816 -0.14462322 -0.1146795 ]
[ 0.18340037 -0.01225733 -0.14691681  0.12910865]
[ 0.18315523 -0.20500262 -0.14433464  0.37207362]
[ 0.17905517 -0.39781079 -0.13689317  0.61599139]
[ 0.17109896 -0.20106864 -0.12457334  0.28351801]
[ 0.16707758 -0.00441045 -0.11890298 -0.04571326]
[ 0.16698938  0.19219805 -0.11981725 -0.37341889]
[ 0.17083334 -0.00103619 -0.12728562 -0.12078767]
[ 0.17081261 -0.19412647 -0.12970138  0.12918363]
[ 0.16693008  0.0025919  -0.1271177  -0.20144083]
[ 0.16698192  0.19928101 -0.13114652 -0.53136602]
[ 0.17096754  0.39598015 -0.14177384 -0.86232768]
[ 0.17888714  0.20304365 -0.1590204  -0.61736858]
[ 0.18294802  0.39998771 -0.17136777 -0.95561257]
[ 0.19094777  0.20753317 -0.19048002 -0.72129514]


In [ ]:
# now we will implement hill climbing algorithm. Hill climbing initializes random weights, then uses memory
# to save good weights

# here we will not use sample action, rather create our random action and update our own 
# random;y initialized weights

# function for creating and running an episode
def episode(env, weights):
    
    observation = env.reset()
    totalReward = 0
    
    #we will make 200 time steps in an episode
    for tSteps in range(200):
        
        env.render()
        
        #now if the multiplication of our weights and observation is -ve, we will go left (action 0)
        # otherwise we ll go right (action 1)
        
        action = 0 if np.matmul(observation, weights) <0 else 1:
        